/*
JavaScript Horizontal Image Slider Gold 2.0
(C)1999-2008 Usingit.com, All rights reserved!
http://www.usingit.com/products/webtoolkit
http://www.usingit.com/support
*/
CIlogo(['Careimages/Clientlist/slider0.gif','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',57,50]);
CIlogo(['Careimages/Clientlist/slider1.gif','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',146,55]);
CIlogo(['Careimages/Clientlist/slider2.jpg','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',56,55]);
CIlogo(['Careimages/Clientlist/slider3.gif','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',56,55]);
CIlogo(['Careimages/Clientlist/slider4.jpg','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',57,55]);
CIlogo(['Careimages/Clientlist/slider5.jpg','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',245,40]);
CIlogo(['Careimages/Clientlist/slider6.gif','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',210,35]);
CIlogo(['Careimages/Clientlist/slider7.gif','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',50,50]);
CIlogo(['Careimages/Clientlist/slider8.jpg','','_self','This script was generated by JavaScript Horizontal Image Slider Gold from usingit.com!',51,50]);
function CIlogo(ipa){
if(!(window.logocfg)){eval('window.logocfg=new Array();');};
logocfg[logocfg.length]=ipa;};
function Initlogo(){
if (!window.Beav){setTimeout('Initlogo()',350);return;};
new BAau('logo_div',410,55,1,39,10,0,'FFFFFF',logocfg,0,0,1,'../Careimages\Clientlist\loading_w.gif','logo_Loading');};
Initlogo();
